/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get signing nonce for SIWS */
        get: operations["AuthController_getNonce"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify wallet signature and issue JWT */
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange refresh token for new access + refresh tokens */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh token family and sign out */
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List raffles with optional filters and pagination */
        get: operations["RafflesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch fetch off-chain metadata for up to 100 raffle IDs */
        get: operations["RafflesController_getBatchMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get raffle detail by ID
         * @description Returns merged contract and off-chain details for active, ended, or cancelled raffles (200 OK). Returns 404 Not Found for unknown IDs and 410 Gone for soft-deleted or permanently removed raffles.
         */
        get: operations["RafflesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List participants (ticket holders) for a raffle */
        get: operations["RafflesController_getParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/{id}/ipfs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to IPFS metadata */
        get: operations["RafflesController_redirectToIpfs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/{raffleId}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update raffle metadata */
        post: operations["RafflesController_upsertMetadata"];
        /** Soft-delete raffle metadata (creator or admin) */
        delete: operations["RafflesController_deleteMetadata"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/{raffleId}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purchase tickets for a raffle */
        post: operations["RafflesController_purchaseTickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/upload-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload raffle image to storage */
        post: operations["RafflesController_uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/raffles/{id}/og": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RafflesController_getRaffleOgImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/og/default.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OgRenderController_getDefaultOgImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/og/raffles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pre-render OG meta tags for a raffle (for social media crawlers) */
        get: operations["OgRenderController_renderRaffleOg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/raffles/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all archived (soft-deleted) raffle metadata */
        get: operations["AdminRafflesController_getArchived"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/raffles/{raffleId}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin soft-delete of raffle metadata */
        delete: operations["AdminRafflesController_deleteMetadata"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/raffles/{raffleId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore archived raffle metadata */
        post: operations["AdminRafflesController_restoreMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile by Stellar address */
        get: operations["UsersController_getByAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{address}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user raffle participation history */
        get: operations["UsersController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{address}/history/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export full raffle participation history as CSV */
        get: operations["UsersController_exportHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top participants leaderboard */
        get: operations["LeaderboardController_getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get platform-wide aggregates */
        get: operations["StatsController_getPlatformStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/transparency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_getTransparencyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_verifyDrawByTxHash"];
        put?: never;
        post: operations["StatsController_verifyDraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to raffle notifications */
        post: operations["NotificationsController_subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/subscribe/{raffleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unsubscribe from raffle notifications */
        delete: operations["NotificationsController_unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a notification subscription */
        put: operations["NotificationsController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all raffle subscriptions for the authenticated user */
        get: operations["NotificationsController_getUserSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/device-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a FCM device token for push notifications */
        post: operations["NotificationsController_registerDeviceToken"];
        /** Unregister a FCM device token */
        delete: operations["NotificationsController_unregisterDeviceToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notification preferences for the authenticated user */
        get: operations["NotificationsController_getPreferences"];
        /** Update notification preferences for the authenticated user */
        put: operations["NotificationsController_updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for raffles */
        get: operations["SearchController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SupportController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetricsController_getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get background jobs status */
        get: operations["MonitorController_getJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system monitoring stats */
        get: operations["MonitorController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system latency metrics */
        get: operations["MonitorController_getLatency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system error logs */
        get: operations["MonitorController_getErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system audit logs */
        get: operations["MonitorController_getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an async indexer backfill */
        post: operations["MonitorController_startBackfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/backfill/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get async indexer backfill job status */
        get: operations["MonitorController_getBackfillStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitor/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get maintenance mode status */
        get: operations["MonitorController_getMaintenanceMode"];
        /** Set maintenance mode status */
        put: operations["MonitorController_setMaintenanceMode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a ledger replay job
         * @description Triggers an async replay of ledgers in the specified range. Returns a job ID for polling progress.
         */
        post: operations["ReplayController_startReplay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/replay/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get replay job status
         * @description Poll the status and progress of a replay job.
         */
        get: operations["ReplayController_getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhooks for the current user */
        get: operations["WebhooksController_getWebhooks"];
        put?: never;
        /** Create a new webhook subscription */
        post: operations["WebhooksController_createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific webhook by ID */
        get: operations["WebhooksController_getWebhook"];
        /** Update a webhook */
        put: operations["WebhooksController_updateWebhook"];
        post?: never;
        /** Delete a webhook */
        delete: operations["WebhooksController_deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent delivery logs for a webhook */
        get: operations["WebhooksController_getDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VerifyBodyDto: {
            /** @description Stellar address of the user */
            address: string;
            /** @description Wallet signature of the SIWS message */
            signature: string;
            /** @description Nonce obtained from /auth/nonce */
            nonce: string;
            /** @description Timestamp the signature was issued */
            issuedAt?: string;
        };
        RefreshBodyDto: {
            /** @description Refresh token previously issued by the server */
            refreshToken: string;
        };
        SignOutBodyDto: {
            /** @description Refresh token to revoke (signs out the session) */
            refreshToken: string;
        };
        ParticipantDto: {
            /**
             * @description Stellar address of the ticket holder
             * @example GABCDEFGHIJKLMNOPQRSTUVWXYZ234567
             */
            address: string;
            /**
             * @description Number of tickets purchased by this address for this raffle
             * @example 5
             */
            tickets_count: number;
            /**
             * @description Unix timestamp (in seconds) when the first ticket was purchased
             * @example 1234567890
             */
            purchased_at: number;
        };
        ParticipantListResponseDto: {
            /** @description List of participants (ticket holders) for the raffle */
            participants: components["schemas"]["ParticipantDto"][];
            /**
             * @description Total number of unique participants
             * @example 42
             */
            total: number;
            /**
             * @description Number of records returned in this page
             * @example 10
             */
            limit: number;
            /**
             * @description Number of records skipped
             * @example 0
             */
            offset: number;
        };
        UpsertMetadataDto: {
            /** @description Title of the raffle */
            title?: string;
            /** @description Description text */
            description?: string;
            /**
             * Format: uri
             * @description Primary image URL (http or https only)
             */
            image_url?: string;
            /** @description Additional image URLs (http or https only, max 10) */
            image_urls?: string[];
            /** @description Category name */
            category?: string;
            /** @description IPFS CID for metadata */
            metadata_cid?: string;
            /** @description Asset used for ticket pricing (code must be whitelisted) */
            asset?: {
                /** @example USDC */
                code?: string;
                /** @example GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN */
                issuer?: string;
            };
        };
        PurchaseTicketDto: {
            /** @description Number of tickets to purchase */
            quantity: number;
        };
        Function: Record<string, never>;
        BackfillRequestDto: {
            /** @description Inclusive starting ledger */
            fromLedger: number;
            /** @description Inclusive ending ledger */
            toLedger: number;
        };
        SetMaintenanceModeDto: {
            /** @description Enable or disable maintenance mode */
            enabled: boolean;
        };
        ReplayJobStartResponseDto: {
            /** @description Generated job identifier */
            jobId: string;
            /** @description Human-readable job status message */
            message: string;
        };
        ReplayJobConfigDto: {
            /** @description First ledger included in the replay */
            fromLedger: number;
            /** @description Last ledger included in the replay */
            toLedger: number;
            /** @description Optional contract ID to limit the replay */
            contractId?: string;
            /** @description Whether the replay is dry-run only */
            dryRun?: boolean;
            /** @description Explicit confirmation for mutating replay runs */
            confirmed?: boolean;
        };
        ReplayJobProgressDto: {
            /** @description Number of ledgers processed so far */
            processedCount: number;
            /** @description Number of ledgers skipped so far */
            skippedCount: number;
            /** @description Total ledgers in the replay range */
            totalLedgers: number;
            /** @description Currently processed ledger number */
            currentLedger?: number;
        };
        ReplayPlannedActionDto: {
            /** @description Ledger number for this action */
            ledger: number;
            /**
             * @description Planned action outcome
             * @enum {string}
             */
            action: "submit" | "skip";
            /** @description Reason for the action */
            reason?: string;
        };
        ReplayJobResultDto: {
            /** @description Elapsed execution time in milliseconds */
            elapsedMs: number;
            /** @description Ledger numbers that were not replayed */
            missingLedgers: number[];
            /** @description Planned actions taken during the replay */
            plannedActions?: components["schemas"]["ReplayPlannedActionDto"][];
            /** @description Total ledgers in the replay range */
            totalLedgers?: number;
            /** @description First ledger included in the replay */
            fromLedger?: number;
            /** @description Last ledger included in the replay */
            toLedger?: number;
            /** @description Number of ledgers processed */
            processedCount?: number;
            /** @description Number of ledgers skipped */
            skippedCount?: number;
        };
        ReplayJobStatusDto: {
            /** @description Generated job identifier */
            jobId: string;
            /**
             * @description Replay job state
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            config: components["schemas"]["ReplayJobConfigDto"];
            progress: components["schemas"]["ReplayJobProgressDto"];
            result?: components["schemas"]["ReplayJobResultDto"];
            /** @description Failure reason if the replay failed */
            error?: string;
            /** @description ISO timestamp when the job was created */
            createdAt: string;
            /** @description ISO timestamp when the job started */
            startedAt?: string;
            /** @description ISO timestamp when the job completed */
            completedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_getNonce: {
        parameters: {
            query: {
                /** @description Stellar address of the user */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshBodyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignOutBodyDto"];
            };
        };
        responses: {
            /** @description Session revoked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sign-out failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_list: {
        parameters: {
            query?: {
                /** @description Filter by raffle status */
                status?: string;
                /** @description Filter by raffle category */
                category?: string;
                /** @description Filter by raffle creator — must be a valid Stellar public key */
                creator?: string;
                /** @description Filter by asset code (1–12 alphanumeric characters) */
                asset?: string;
                /** @description Number of records to return */
                limit?: number;
                /** @description Number of records to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raffles list retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_getBatchMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Batch metadata retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal raffle ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raffle details retrieved successfully (active, ended, or cancelled) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Raffle not found (unknown ID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Raffle has been soft-deleted or permanently removed */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_getParticipants: {
        parameters: {
            query?: {
                /** @description Max 100, default 20 */
                limit?: number;
                /** @description Offset for pagination, default 0 */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Internal raffle ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participants list retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantListResponseDto"];
                };
            };
        };
    };
    RafflesController_redirectToIpfs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal raffle ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirected to IPFS URL */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description IPFS metadata not found for raffle */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_upsertMetadata: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID for safe retries. Prevents duplicate metadata writes if request is retried within 24 hours. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Internal raffle ID */
                raffleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertMetadataDto"];
            };
        };
        responses: {
            /** @description Metadata created/updated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict — request with this Idempotency-Key is already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_deleteMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal raffle ID */
                raffleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata soft-deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — not the creator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Raffle or metadata not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_purchaseTickets: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated unique key for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Internal raffle ID */
                raffleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseTicketDto"];
            };
        };
        responses: {
            /** @description Ticket purchase submitted, returns transaction hash */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional raffle ID (defaults to 'draft') */
                    raffleId?: string;
                };
            };
        };
        responses: {
            /** @description Image uploaded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RafflesController_getRaffleOgImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OgRenderController_getDefaultOgImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OgRenderController_renderRaffleOg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Raffle ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminRafflesController_getArchived: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived metadata retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminRafflesController_deleteMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal raffle ID */
                raffleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata soft-deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Active metadata not found for raffle */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminRafflesController_restoreMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal raffle ID */
                raffleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata restored successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archived metadata not found for raffle */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getByAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stellar address of the user */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getHistory: {
        parameters: {
            query?: {
                /** @description Number of records to return */
                limit?: number;
                /** @description Number of records to skip */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Stellar address of the user */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User history retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_exportHistory: {
        parameters: {
            query?: {
                /** @description Export format (csv) */
                format?: "csv";
            };
            header?: never;
            path: {
                /** @description Stellar address of the user */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded — 1 export per minute */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LeaderboardController_getLeaderboard: {
        parameters: {
            query?: {
                /** @description Sort field */
                by?: "wins" | "volume" | "tickets";
                /** @description Number of entries */
                limit?: number;
                /** @description Cursor for cursor-based pagination */
                cursor?: string;
                /** @description Offset for offset-based pagination (deprecated) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatsController_getPlatformStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform stats retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatsController_getTransparencyStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatsController_verifyDrawByTxHash: {
        parameters: {
            query: {
                txHash: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatsController_verifyDraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Function"];
            };
        };
        responses: {
            /** @description Subscription created or returned if already exists */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                raffleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unsubscribed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Function"];
            };
        };
        responses: {
            /** @description Subscription updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_getUserSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_registerDeviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Function"];
            };
        };
        responses: {
            /** @description Token registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_unregisterDeviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Function"];
            };
        };
        responses: {
            /** @description Token removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User notification preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    NotificationsController_updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Function"];
            };
        };
        responses: {
            /** @description Preferences updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SearchController_search: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                limit?: number;
                offset?: number;
                /** @description Filter by category */
                category?: string;
                /** @description Filter by status */
                status?: string;
                /** @description Sort order for results */
                sort?: "relevance" | "ending_soon" | "price_asc" | "most_tickets";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SupportController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetricsController_getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_getJobs: {
        parameters: {
            query?: {
                /** @description Job status */
                status?: "pending" | "completed" | "failed";
                /** @description Number of jobs to return */
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System stats retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_getLatency: {
        parameters: {
            query?: {
                /** @description Start datetime (ISO 8601) */
                from?: string;
                /** @description End datetime (ISO 8601) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latency metrics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_getErrors: {
        parameters: {
            query?: {
                /** @description Number of errors to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Errors retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_getAuditLogs: {
        parameters: {
            query?: {
                /** @description Start datetime (ISO 8601) */
                from?: string;
                /** @description End datetime (ISO 8601) */
                to?: string;
                /** @description Number of logs to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_startBackfill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequestDto"];
            };
        };
        responses: {
            /** @description Backfill job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        jobId?: string;
                    };
                };
            };
        };
    };
    MonitorController_getBackfillStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backfill job status retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "running" | "completed" | "failed";
                        processedLedgers?: number;
                    };
                };
            };
        };
    };
    MonitorController_getMaintenanceMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Maintenance mode status retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MonitorController_setMaintenanceMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMaintenanceModeDto"];
            };
        };
        responses: {
            /** @description Maintenance mode status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReplayController_startReplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayJobStartResponseDto"];
                };
            };
            /** @description Invalid replay configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReplayController_getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayJobStatusDto"];
                };
            };
            /** @description Invalid or missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_getWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhooksController_getDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
