export interface FAQItem {
  question: string;
  answer: string;
}

export interface FAQCategory {
  title: string;
  items: FAQItem[];
}

export type FAQData = FAQCategory;

export const faqData: FAQData[] = [
  {
    title: "Wallets",
    items: [
      {
        id: "wallet-support",
        question: "Which wallets are supported by the platform?",
        answer: "We support major Stellar-compatible wallets, including Freighter, xBull, and Albedo. We highly recommend using Freighter for the smoothest experience on Soroban smart contract networks."
      },
      {
        question: "How do I connect my Freighter wallet?",
        answer: "Click the 'Connect Wallet' button in the top right navigation bar, select 'Freighter' from the modal options, and approve the connection request popup inside your Freighter extension window."
      },
      {
        question: "Why is my wallet showing the wrong network?",
        answer: "Ensure your wallet extension is toggled to the network matching our platform (e.g., Testnet for testing or Mainnet for live draws). You can switch networks in your wallet extension's settings panel."
      }
    ]
  },
  {
    title: "Tickets & Raffles",
    items: [
      {
        id: "how-to-buy",
        question: "How do I buy a ticket?",
        answer: "To buy a ticket, connect your Stellar-compatible wallet (like Albedo or Rabbit), select the lottery you wish to enter, and click 'Purchase'. You will need a small amount of XLM for the transaction fee."
      },
      {
        question: "Can I buy multiple tickets for a single raffle?",
        answer: "Yes! There is no limit on how many tickets a single wallet address can purchase, provided the raffle's max ticket pool capacity hasn't been hit. More tickets grant a proportionally higher mathematical probability of winning."
      },
      {
        question: "What is the refund policy if a raffle is cancelled?",
        answer: "If a raffle is cancelled or fails to reach its minimum threshold criteria before the expiration deadline, the Soroban smart contract enters a refundable state. You can claim a 100% refund of your ticket purchase cost directly through the user interface."
      },
      {
        question: "Are my tickets transferable after purchase?",
        answer: "No. Raffle tickets are bound directly to the minting/purchasing wallet address on-chain and cannot be traded or transferred to another account."
      }
    ]
  },
  {
    title: "Randomness & Oracle Mechanisms",
    items: [
      {
        question: "How is the winner chosen?",
        answer: "Winners are drawn using an automated execution triggered on the Soroban smart contract. The system pulls an external entropy payload generated by a secure decentralized oracle framework to dictate the winning ticket index impartially."
      },
      {
        question: "What is a VRF proof?",
        answer: "A Verifiable Random Function (VRF) proof is a cryptographic proof that demonstrates a random number was generated purely from a secret seed and public key parameters. It guarantees the output is mathematically unpredictable, tamper-proof, and fully verifiable by anyone on-chain."
      },
      {
        question: "Can developers or creators rig the outcome?",
        answer: "No. Because the calculation runs entirely within an open-source Soroban smart contract coupled with verifiable VRF oracles, neither platform operators nor raffle creators can manipulate the generation sequence."
      }
    ]
  },
  {
    title: "Fees & Network Gas",
    items: [
      {
        question: "What are the transaction fees on the platform?",
        answer: "Every ticket purchase and interaction relies on the Stellar network's native fee structure. Soroban smart contracts require execution fees ('resource fees') paid in XLM. These are highly scalable and typically cost a fraction of a cent."
      },
      {
        question: "Who pays for the oracle random number generation?",
        answer: "The platform covers or subsidizes the base operational infrastructure overhead of pulling the oracle feed into the smart contract state, ensuring users only handle their standard ticket purchase interaction gas."
      },
      {
        question: "What happens if my transaction fails due to low fees?",
        answer: "If your wallet sets too low of an XLM base fee during high network utilization spikes, the transaction will time out. Simply bump your max fee parameter in Freighter and retry."
      }
    ]
  },
  {
    title: "Transparency & Security",
    items: [
      {
        question: "Where can I verify the draw on-chain?",
        answer: "Every single raffle deployment, ticket purchase execution, and winning draw logs an event stream to the ledger. You can verify all steps by inspecting the specific Soroban Contract ID on network block explorers like StellarExpert."
      },
      {
        question: "Is the raffle contract open-source?",
        answer: "Yes, our Soroban Rust smart contracts are completely open-source. Anyone can audit the logic, structural parameters, state machines, and cryptographic verification mechanisms on our official GitHub organization."
      },
      {
        question: "How long after the countdown does the automated draw happen?",
        answer: "Once the deadline timestamp passes, an on-chain execution call is initiated. The process relies on blockchain block confirmation times, usually triggering and resolving inside 5 to 10 seconds."
      }
    ]
  }
];
