-- Baseline schema for Tikka platform
-- Generated by: npm run db:check-drift -- update-baseline
-- 
-- This file represents the expected schema after running ALL committed
-- migrations (backend, indexer, oracle) against a fresh PostgreSQL instance.
--
-- IMPORTANT: Update this file whenever a schema-changing migration is merged.
--   1. Merge the migration PR
--   2. Run: npm run db:check-drift -- update-baseline
--   3. Commit the updated baseline-schema.sql
--
-- CI will reject PRs that cause drift between this baseline and a fresh
-- migration run. If CI fails with a drift error on a migration PR, run the
-- update command above and push the baseline change as part of your PR.

-- Enforce read-only access from backend to indexer-owned tables.
DO $$
DECLARE
    table_name text;
    indexer_tables text[] := ARRAY['raffle', 'participant'];
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'backend_reader') THEN
        CREATE ROLE backend_reader NOLOGIN;
    END IF;

    GRANT USAGE ON SCHEMA public TO backend_reader;

    FOREACH table_name IN ARRAY indexer_tables
    LOOP
        IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = table_name) THEN
            EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE public.%I FROM backend_reader', table_name);
            EXECUTE format('GRANT SELECT ON TABLE public.%I TO backend_reader', table_name);
        END IF;
    END LOOP;
END $$;